Create CI/CD pipeline with GitHub Actions for developer-assessment coding test
ClearPointNZ/developer-assessment pull request #8
Opened 2023-01-26 01:57 UTC by pradhanangan

JIRA: https://clearpoint.atlassian.net/browse/ENP-293

__Changes__
Created simple CI/CD pipeline using github actions to build and run unit test Backend and Frontend application. Currently it run on every push request.
Dockerized the Backend application

__New File:__
.github/workflows/main.yaml
Frontend/Dockerfile
tasks (Bash file)

__Modified File:__
Frontend/package.json
The line was added because testing Frontend app using jest was throwing error
`Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.`
and axios node module uses non standard Javascript syntax.

2023-01-26 04:28 UTC, mhurbuns commented on .github/workflows/main.yaml
> +      - run: ./tasks e2e
e2e is not needed

2023-01-26 04:28 UTC, mhurbuns commented on tasks
> +image_registry="${image_registry_prefix}.azurecr.io"
remove

2023-01-26 04:30 UTC, mhurbuns requested changes
Good start. Remove e2e references. 
We need build and test tasks

2023-01-27 00:14 UTC, pradhanangan commented
> Good start. Remove e2e references. We need build and test tasks

@mhurbuns, updated code.

2023-03-14 20:18 UTC, michaelm-clearpoint submitted a review, later dismissed

2023-03-16 20:11 UTC, mniem approved these changes
LGTM

2023-03-16 20:14 UTC, merged